### ISSUE TITLE
complex-sv with external assembly contigs

### ISSUE THREAD

**Issue by cbi-star** [maiziezhoulab/VolcanoSV#10]
When an external whole genome assembly contigs (hp1.fa and hp2.fa) are used, we need to comment out the line 106 in your script: volcanosv-vc-complex-sv.py like this:

logger.info("-------------------------------Skip Merge contigs for external whole genome assembly ")
#merge_fasta(input_dir,out_dir)

**Comment by volcano1998** [comment]
I just included this function in the session "Use VolcanoSV-vc for other assemblies" in the Readme as well. Thank you so much!
