### ISSUE TITLE
validate called Structural Variants

### ISSUE THREAD

**Issue by DayTimeMouse** [maiziezhoulab/VolcanoSV#11]
Hi,

How can I further validate called Structural Variants (SVs) besides using IGV, especially when the number of SV variants may be in the hundreds or even thousands? Could you give me some ideas?

Best regards.

**Comment by volcano1998** [comment]
Hi @DayTimeMouse , that's a good question.  It is always hard to validate SV calls when there is no gold standard available.  I'm not an expert on validating SV but here are some of my thoughts: you may check other SV call databases to perform orthogonal comparison, for example, comparing your SV call to other SV callset of apes (ancestral state), or comparing it to other human SV database such as Nomad.
