### ISSUE TITLE
volcanosv-vc-large-indel.py fails

### ISSUE THREAD

**Issue by byoo** [maiziezhoulab/VolcanoSV#3]
Hello, I would like to ask help in running volcanosv-vc-large-indel.py
I have run the script as follows. It started with assertion errors and failed eventually. [test_large-indel.sh.log](https://github.com/user-attachments/files/17468093/test_large-indel.sh.log)

Could you advise on troubleshooting the issue? Thank you.

```
$python3 ${volcanosv_vc_large_indel_py} \
	-bam $bam \
	-i $inputdir \
	-o $outputdir \
	-ref $reference \
	-t 4 \
	-chr 21 \
	-dtype Hifi \
	-px $sample
```

**Comment by volcano1998** [comment]
Thank you for trying out our tool! Could you please show me the error message? A screenshot would be nice. Thanks!

**Comment by volcano1998** [comment]
Thank you for trying our tool!

I reviewed your log file and found the problem might be that my code did not consider the "skipped region" in cigar operation. I just added that part. Could you try git pull and rerun your experiment?

Let me know if the error persists. Thanks!

**Comment by byoo** [comment]
Thank you for the quick help! Unfortunately, it didn't resolve the issue.

The first assertion error I got is this, and I added some debug information FYI:

```
assert offset_ref==read.reference_end, f"{read.qname}; {read.cigar}, {offset_ref}!={read.reference_end}"
```
AssertionError: m84052_231020_195028_s4/160497931/ccs; [(7, 78), (2, 1), (7, 120), (2, 1), (7, 798), (8, 1), (7, 787), (1, 8), (7, 350), (2, 1), (7, 38), (2, 1), (7, 97), (8, 1), (7, 257), (1, 1), (7, 124), (2, 1), (8, 1), (7, 287), (8, 1), (7, 196), (8, 1), (7, 506), (1, 1), (7, 460), (8, 1), (7, 39), (2, 1), (7, 384), (8, 1), (7, 151), (2, 1), (7, 8), (8, 1), (7, 156), (1, 1), (7, 137), (2, 1), (7, 102), (2, 1), (7, 257), (1, 1), (7, 433), (2, 1), (7, 454), (2, 1), (7, 223), (2, 1), (7, 674), (2, 1), (7, 477), (8, 1), (7, 238), (2, 1), (7, 456), (2, 1), (7, 33), (2, 1), (7, 310), (2, 1), (7, 614), (2, 1), (7, 512), (2, 1), (7, 125), (1, 1), (7, 385), (1, 1), (7, 74), (2, 1), (7, 16), (2, 1), (7, 1208), (8, 1), (7, 566), (2, 1), (7, 962), (2, 1), (7, 581), (8, 1), (7, 165), (1, 1), (7, 363), (2, 1), (7, 38), (1, 1), (7, 202), (2, 1), (7, 110), (1, 1), (7, 38), (2, 1), (7, 19), (1, 1), (7, 273)], 5051071!=5065963

**Comment by volcano1998** [comment]
Thank you for helping diagnosing the problem! You are right, the problem is not skipped region but the sequence match(7)/mismatch(8). I only considered alignment match "0" in the script. Just updated the script and you may git pull again!

Thanks!

**Comment by byoo** [comment]
It made progress! It proceeded until it encountered an assertion error during the read length comparison.
Please let me know if there is something I can provide.

https://github.com/maiziezhoulab/VolcanoSV/blob/f197d9cfc32cd6df5cd5852bd3e90a1d9e84446e/bin/VolcanoSV-vc/Large_INDEL/extract_reads_signature.py#L171

**Comment by volcano1998** [comment]
Ops. Sorry, that part is also due to the cigar 7/8. I just quickly browsed my script and (I believe) now everything is updated for cigar 7/8, hopefully.

Please try again and let me know how it goes!

Thank you for your patience!

**Comment by byoo** [comment]
I confirmed that the test run finished successfully.
Thanks again for sharing your work and prompt help!

**Comment by volcano1998** [comment]
Thank you for being supportive!
