### ISSUE TITLE
volcanosv-vc-complex-sv.py fails

### ISSUE THREAD

**Issue by byoo** [maiziezhoulab/VolcanoSV#4]
Hello,

I'd like to report that volcanosv-vc-complex-sv.py fails to run on hifi reads.
volcanosv-vc-complex-sv.py expects "Hifi" as the data type and pass the value to align_ins2ref.py. But align_ins2ref.py expects "CCS" and fails due to the undefined "Hifi". Could you fix the issue? Thanks!

https://github.com/maiziezhoulab/VolcanoSV/blob/648788c550e524b3ea1c82f919cd0ccfce3bd26e/bin/VolcanoSV-vc/Complex_SV/volcanosv-vc-complex-sv.py#L10

https://github.com/maiziezhoulab/VolcanoSV/blob/648788c550e524b3ea1c82f919cd0ccfce3bd26e/bin/VolcanoSV-vc/Complex_SV/align_ins2ref.py#L10

**Comment by byoo** [comment]
Just to update, I could run the test successfully after changing `CCS` to `Hifi` here:

https://github.com/maiziezhoulab/VolcanoSV/blob/648788c550e524b3ea1c82f919cd0ccfce3bd26e/bin/VolcanoSV-vc/Complex_SV/align_ins2ref.py#L10

Additionally, I'd like to point out that the number of threads for `samtools` in the code below is hard-coded to 20, which might lead to unexpectedly high resource usage, regardless of the number of threads specified for `volcanosv-vc-complex-sv.py`. Ideally, IMHO, `align_ins2ref.py` should not use more threads than those allocated for `volcanosv-vc-complex-sv.py`.

https://github.com/maiziezhoulab/VolcanoSV/blob/648788c550e524b3ea1c82f919cd0ccfce3bd26e/bin/VolcanoSV-vc/Complex_SV/align_ins2ref.py#L67

**Comment by volcano1998** [comment]
Hi, I just fixed both issues. Thanks a lot for diagnosing the problem!

**Comment by byoo** [comment]
Thank you again for the quick fix!
