### ISSUE TITLE
volcanosv-vc-small-indel.py and volcanosv-vc-large-indel.py fail on hifi reads

### ISSUE THREAD

**Issue by byoo** [maiziezhoulab/VolcanoSV#5]
Hello,

We are continuing to test VolcanoSV on hifi reads and got the error below in running `volcanosv-vc-small-indel.py`.
Could you help resolve the issue?

```
****************************************

    check kmer support and remove false call

****************************************
100%|██████████| 594495/594495 [2:28:05<00:00, 66.91it/s]
/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL/check_reads_kmer_support.py:272: RuntimeWarning: Mean of empty slice.
  zero_rate = ((np.array(cnt_list)<= min_support )).mean()
/software/python/current/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
```

In addition, I'd like to report that when the optional `--region` argument is not used for `volcanosv-vc-small-indel.py`, it is still passed into `htsbox pileup` as `-r None`. While this seems harmless, it might not be intentional and it gives the following warning:
` [fai_fetch] Warning - Reference None not found in FASTA file, returning empty sequence`

Thank you!

**Comment by byoo** [comment]
`volcanosv-vc-large-indel.py` also failed and below is the bottom of the log.
Please let me know if there is something I can help you further.

```
2024-10-26 19:35:02 INFO     ------------------Use empirical threshold to filter SV
2024-10-26 19:35:03 INFO     ------------------Correct DEL GT
num of sig:  251999
extract sig support: 100%|██████████| 13549/13549 [00:00<00:00, 41299.15it/s]
check around breakpoint read depth: 100%|██████████| 13549/13549 [01:00<00:00, 224.54it/s]
/software/VolcanoSV/current/bin/VolcanoSV-vc/Large_INDEL/correct_gt_del_real_data.py:208: RuntimeWarning: divide by zero encountered in true_divide
  n_ratio_list = num_sup_list / depth_list
/software/VolcanoSV/current/bin/VolcanoSV-vc/Large_INDEL/correct_gt_del_real_data.py:208: RuntimeWarning: invalid value encountered in true_divide
  n_ratio_list = num_sup_list / depth_list
2024-10-26 19:36:06 INFO     ------------------Correct INS GT
loading sigfile /analysis/cloud_projects/research/pacbio/cbi/VolvanoSV/GRCh38/cmh001988-01/volcanosv_large_indel_output/cute_sig/INS.sigs...
num different signature:  142414
100%|██████████| 20461/20461 [00:00<00:00, 62992.96it/s]
check reads coverage: 100%|██████████| 20461/20461 [01:33<00:00, 218.06it/s]
sort -k1,1d -k2,2n
```

**Comment by byoo** [comment]
`volcanosv-vc-large-indel.py` also failed and below is the bottom of the log.
Please let me know if there is something I can help you further.

```
2024-10-26 19:35:02 INFO     ------------------Use empirical threshold to filter SV
2024-10-26 19:35:03 INFO     ------------------Correct DEL GT
num of sig:  251999
extract sig support: 100%|██████████| 13549/13549 [00:00<00:00, 41299.15it/s]
check around breakpoint read depth: 100%|██████████| 13549/13549 [01:00<00:00, 224.54it/s]
/software/VolcanoSV/current/bin/VolcanoSV-vc/Large_INDEL/correct_gt_del_real_data.py:208: RuntimeWarning: divide by zero encountered in true_divide
  n_ratio_list = num_sup_list / depth_list
/software/VolcanoSV/current/bin/VolcanoSV-vc/Large_INDEL/correct_gt_del_real_data.py:208: RuntimeWarning: invalid value encountered in true_divide
  n_ratio_list = num_sup_list / depth_list
2024-10-26 19:36:06 INFO     ------------------Correct INS GT
loading sigfile /analysis/cloud_projects/research/pacbio/cbi/VolvanoSV/GRCh38/cmh001988-01/volcanosv_large_indel_output/cute_sig/INS.sigs...
num different signature:  142414
100%|██████████| 20461/20461 [00:00<00:00, 62992.96it/s]
check reads coverage: 100%|██████████| 20461/20461 [01:33<00:00, 218.06it/s]
sort -k1,1d -k2,2n
```

**Comment by volcano1998** [comment]
> `volcanosv-vc-large-indel.py` also failed and below is the bottom of the log. Please let me know if there is something I can help you further.
> 
> ```
> 2024-10-26 19:35:02 INFO     ------------------Use empirical threshold to filter SV
> 2024-10-26 19:35:03 INFO     ------------------Correct DEL GT
> num of sig:  251999
> extract sig support: 100%|██████████| 13549/13549 [00:00<00:00, 41299.15it/s]
> check around breakpoint read depth: 100%|██████████| 13549/13549 [01:00<00:00, 224.54it/s]
> /software/VolcanoSV/current/bin/VolcanoSV-vc/Large_INDEL/correct_gt_del_real_data.py:208: RuntimeWarning: divide by zero encountered in true_divide
>   n_ratio_list = num_sup_list / depth_list
> /software/VolcanoSV/current/bin/VolcanoSV-vc/Large_INDEL/correct_gt_del_real_data.py:208: RuntimeWarning: invalid value encountered in true_divide
>   n_ratio_list = num_sup_list / depth_list
> 2024-10-26 19:36:06 INFO     ------------------Correct INS GT
> loading sigfile /analysis/cloud_projects/research/pacbio/cbi/VolvanoSV/GRCh38/cmh001988-01/volcanosv_large_indel_output/cute_sig/INS.sigs...
> num different signature:  142414
> 100%|██████████| 20461/20461 [00:00<00:00, 62992.96it/s]
> check reads coverage: 100%|██████████| 20461/20461 [01:33<00:00, 218.06it/s]
> sort -k1,1d -k2,2n
> ```

Just resolved this one

**Comment by volcano1998** [comment]
> Hello,
> 
> We are continuing to test VolcanoSV on hifi reads and got the error below in running `volcanosv-vc-small-indel.py`. Could you help resolve the issue?
> 
> ```
> ****************************************
> 
>     check kmer support and remove false call
> 
> ****************************************
> 100%|██████████| 594495/594495 [2:28:05<00:00, 66.91it/s]
> /software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL/check_reads_kmer_support.py:272: RuntimeWarning: Mean of empty slice.
>   zero_rate = ((np.array(cnt_list)<= min_support )).mean()
> /software/python/current/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
>   ret = ret.dtype.type(ret / rcount)
> ```
> 
> In addition, I'd like to report that when the optional `--region` argument is not used for `volcanosv-vc-small-indel.py`, it is still passed into `htsbox pileup` as `-r None`. While this seems harmless, it might not be intentional and it gives the following warning: ` [fai_fetch] Warning - Reference None not found in FASTA file, returning empty sequence`
> 
> Thank you!

I just fixed the `-r None` issue.

For the empty slice warning, that list should not be empty in my intended design, so I added debugger to print out the variant information when that happens. Can you try git pull, rerun it and tell me what  the debug information says, please?

Thanks a lot for your patience!

**Comment by byoo** [comment]
Ok, I'll try the updates and keep you posted. Thank you!

**Comment by byoo** [comment]
Good morning, below is the end of the log after running with the latest.

```
Traceback (most recent call last):
  File "/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL/volcanosv-vc-small-indel.py", line 244, in <module>
    call_var(
  File "/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL/volcanosv-vc-small-indel.py", line 174, in call_var
    filter_indel(prefix, filtered_vcf_path , f'{output_dir}/indel_2_49_context.txt' , read_bam,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL/check_reads_kmer_support.py", line 205, in filter_indel
    if len(len(sequences[i])) == 0:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
```

**Comment by volcano1998** [comment]
I'm so sorry. My debugger has a bug. I fixed it. Can you try it again please?

Really appreciate your patience!!

**Comment by byoo** [comment]
Sure, I updated and started running the test.
Also, I'd like to report that it uses PAR regions from GRCh37 (hs37d5.PAR.bed) as below. 

/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//k8 /sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//dipcall//dipcall-aux.js vcfpair  -p /sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//dipcall/data/**hs37d5.PAR.bed**         ./var_raw.pair.vcf.gz | /sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//htsbox/htsbox bgzip > ./var_raw.dip.vcf.gz

**Comment by byoo** [comment]
Ok, here's the info on the error:

```
****************************************

    check kmer support and remove false call

****************************************
100%|██████████| 594495/594495 [1:51:28<00:00, 88.89it/s]    
encounter empty kmer support array!
Var information:  3627-th var  {'svid': 'chr1-INS-4831-13829918', 'qname': '.', 'contig_seq': 'TTTCCCCCACACGCCCATTTGCCTTC', 'alt': '.'}
```

**Comment by volcano1998** [comment]
I found the problem -- It was because some indels were on the edge of the contig so the Kmer context would be shorter than expected. I just fixed it.

For the par.bed problem, I just added an extra flag "--ref_version" for you to specify which reference version you are using (hg38 or hg37), so the script would choose the bed file accordingly.

Thanks again for bringing out detailed problems!

**Comment by byoo** [comment]
I confirmed that the error doesn't occur with the latest. Thanks again for your prompt help!

**Comment by volcano1998** [comment]
> Sure, I updated and started running the test. Also, I'd like to report that it always uses PAR regions from GRCh37 (hs37d5.PAR.bed) as below.
> 
> /software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//k8 /sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//dipcall//dipcall-aux.js vcfpair -p /sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//dipcall/data/**hs37d5.PAR.bed** ./var_raw.pair.vcf.gz | /sched/software/VolcanoSV/current/bin/VolcanoSV-vc/Small_INDEL//htsbox/htsbox bgzip > ./var_raw.dip.vcf.gz

I further checked this detail. According to Dipcall's github, they only use the par file for male sample to mask out some part of the chromosome X. Since VolcanoSV is only designed for autosome chromosomes, I will remove the par.bed file and also the flag.

**Comment by byoo** [comment]
@volcano1998, do you plan to support sex chromosomes?

**Comment by volcano1998** [comment]
We plan to include XX scenarios for the female sample. For the male sample (XY), it is more complex to phase so it's out of scope for this project.

**Comment by byoo** [comment]
@volcano1998, got it.  Thank you for the clarification!
Additionally, our standard PacBio workflow uses `whatshap` for pedigree-based phasing. Can we use this assembly in VolcanoSV? If so, how can we incorporate external assemblies? Thank you very much for your help!

**Comment by volcano1998** [comment]
You are very welcome!

Yes, you can incorporate other phasing into VolcanoSV. What you need is a phased BAM file, in which every read is associated with a PS and HP tag, so that VolcanoSV can read it for further processing. 

If you have your phased BAM ready, let me know and I will update the general version for you!

**Comment by byoo** [comment]
@volcano1998, thank you very much!
Yes, our standard workflow produces a phased BAM using whatshap and de novo assembly using hifiasm. It would be great if you guide how to take advantage of phased BAM and de novo assembly that we already have, so that we can skip phasing and assembly in VolcanoSV and improve performance/save computational costs.

**Comment by volcano1998** [comment]
Hi @byoo byoo, I'm excited to let you know that I just added a session of "Use VolcanoSV-vc for other assemblies" in the readme. I tested it on 3 datatypes and it worked well. It only needs the phased assembly and a read-to-ref BAM file (either phased or not). Please let me know if you have any problem running it!
