### ISSUE TITLE
take so long time on chr1

### ISSUE THREAD

**Issue by DayTimeMouse** [maiziezhoulab/VolcanoSV#6]
Hi,

I used VolcanoSV to call variants, but it has been stuck on chr1 for more than four days. The program has not reported any errors, and appears that hifiasm is still running. Is this normal?
```
path_to_volcanosv='../VolcanoSV'
for i in {1..22}
do
echo "***********************assembly for chr${i}*******************"
python3 ${path_to_volcanosv}/bin/VolcanoSV-asm/volcanosv-asm.py \
-bam hifi_tumor.bam \
-o volcanosv_asm_output_tumor \
-ref genome.fa \
-t 20 \
-chr ${i} \
-dtype Hifi \
-px tumor \
-asm hifiasm
done
```

Best regards.

**Comment by DayTimeMouse** [comment]
The size of BAM file is 88.12GB.

**Comment by volcano1998** [comment]
I'm glad to hear it move foreward.
Yes, you need to get VCF file for normal and tumor independently, then run survivor to get the somatic SVs.

**Comment by DayTimeMouse** [comment]
Thanks!

I would like to ask when VolcanoSV is expected to support mutation detection on chrX and chrY?

**Comment by DayTimeMouse** [comment]
Hi,

I have occured another problem. 
```
ValueError: too many values to unpack (expected 2)
 38%|█████████████████████████▋                                         | 144066/374930 [1:15:42<2:01:19, 31.72it/s]
```
Please see details in log.
[log.txt](https://github.com/user-attachments/files/17606031/log.txt)


```
path_to_volcanosv=../VolcanoSV
python3 ${path_to_volcanosv}/bin/VolcanoSV-vc/Small_INDEL/volcanosv-vc-small-indel.py \
-i volcanosv_asm_output_tumor \
-o small_indel_output_tumor \
-bam hifi_tumor.bam \
-ref genome.fa \
-t 11 \
-px hifi_tumor
```

**Comment by volcano1998** [comment]
Sorry for not highlighting it in the readme. VolcanoSV is designed only for autosome chromosomes. I just added this to the readme.
